version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bundle_data:/usr/local/bundle
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true

volumes:
  bundle_data:
  pgdata:
