version: '3.8'
services:
  db:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bundle_data:/usr/local/bundle
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  postgres_data:
  bundle_data:
