---
swagger: '2.0'
info:
  title: Metrics API
  version: v1
paths:
  "/api/v1/metrics/aggs/{metric_type}/{frequency}":
    parameters:
    - name: metric_type
      in: path
      type: string
      description: Metric type
      required: true
    - name: frequency
      in: path
      type: string
      description: Frequency
      required: true
    get:
      summary: show aggregates
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    metadata:
                      metric_type:
                        code: electricity_consumption
                        name: Electricity Consumption
                        description: The amount of electricity consumed.
                      frequency: 1d
                      total_pages: 0
                      current_page: 1
                      next_page:
                      prev_page:
                      total_count: 0
                    data: []
        '400':
          description: invalid parameters
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - message: Invalid frequency specified
servers:
- url: http://localhost
  variables:
    defaultHost:
      default: localhost:3000/
